from django.urls import path

from . import views

urlpatterns = [
    path("", views.donate_page, name="donate"),
    path("pay/", views.start_payment, name="pay"),
    path("callback/", views.zarinpal_callback, name="callback"),
    path("overlay/alert/", views.overlay_alert, name="overlay_alert"),
    path("overlay/list/", views.overlay_list, name="overlay_list"),
    path("overlay/goal/", views.overlay_goal, name="overlay_goal"),
    path("overlay/top/", views.overlay_top, name="overlay_top"),
    path("overlay/label/", views.overlay_label, name="overlay_label"),
    path("overlay/total/", views.overlay_total, name="overlay_total"),
    path("overlay/queue/", views.overlay_queue, name="overlay_queue"),
    path("overlay/timer/", views.overlay_timer, name="overlay_timer"),
    path("overlay/snapshot/", views.overlay_snapshot, name="overlay_snapshot"),
    path("panel/login/", views.panel_login, name="panel_login"),
    path("panel/logout/", views.panel_logout, name="panel_logout"),
    path("panel/", views.panel_home, name="panel"),
    path("panel/donations/", views.panel_donations, name="panel_donations"),
    path("panel/gateway/", views.panel_gateway, name="panel_gateway"),
    path("panel/tools/", views.panel_tools, name="panel_tools"),
    path("panel/tools/alert/", views.panel_alert, name="panel_alert"),
    path("panel/tools/goal/", views.panel_goal, name="panel_goal"),
    path("panel/tools/timer/", views.panel_timer, name="panel_timer"),
    path("panel/tools/<slug:slug>/", views.panel_widget, name="panel_widget"),
    path("panel/files/", views.panel_files, name="panel_files"),
    path("panel/conditions/", views.panel_conditions, name="panel_conditions"),
    path("panel/conditions/<int:pk>/update/", views.panel_condition_update, name="panel_condition_update"),
    path("panel/conditions/<int:pk>/delete/", views.panel_condition_delete, name="panel_condition_delete"),
    path("panel/censor/", views.panel_censor, name="panel_censor"),
    path("panel/recap/", views.panel_recap, name="panel_recap"),
    path("panel/stream/", views.panel_stream, name="panel_stream"),
    path("panel/settings/", views.panel_settings, name="panel_settings"),
    path("panel/test/", views.panel_test, name="panel_test"),
    path("panel/skip/", views.panel_skip, name="panel_skip"),
    path("panel/donations/<int:pk>/confirm/", views.panel_confirm_card, name="panel_confirm_card"),
    path("panel/donations/<int:pk>/reject/", views.panel_reject_card, name="panel_reject_card"),
    path("panel/replay/<int:pk>/", views.panel_replay, name="panel_replay"),
    path("panel/live-volume/", views.panel_live_volume, name="panel_live_volume"),
    path("overlay/dock-test/", views.dock_test, name="dock_test"),
    path("overlay/dock-volume/", views.dock_volume, name="dock_volume"),
    path("overlay/dock-skip/", views.dock_skip, name="dock_skip"),
]
