# Generated by Django 6.1 on 2026-08-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='نام')),
                ('amount_toman', models.PositiveIntegerField(verbose_name='مبلغ (تومان)')),
                ('message', models.CharField(blank=True, max_length=280, verbose_name='پیام')),
                ('mobile', models.CharField(blank=True, max_length=15, verbose_name='موبایل')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('paid', 'پرداخت شده'), ('failed', 'ناموفق'), ('test', 'تست')], default='pending', max_length=12, verbose_name='وضعیت')),
                ('authority', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Authority')),
                ('ref_id', models.CharField(blank=True, max_length=64, verbose_name='کد پیگیری')),
                ('is_test', models.BooleanField(default=False, verbose_name='تست')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پرداخت')),
            ],
            options={
                'verbose_name': 'حمایت',
                'verbose_name_plural': 'حمایت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(default='Omid_Atomic', max_length=80, verbose_name='نام نمایشی')),
                ('page_title', models.CharField(default='حمایت از استریم', max_length=120, verbose_name='عنوان صفحه')),
                ('goal_title', models.CharField(default='هدف استریم', max_length=120, verbose_name='عنوان هدف')),
                ('goal_target_toman', models.PositiveIntegerField(default=20000000, verbose_name='هدف (تومان)')),
                ('min_amount_toman', models.PositiveIntegerField(default=10000, verbose_name='حداقل دونیت (تومان)')),
                ('max_amount_toman', models.PositiveIntegerField(default=50000000, verbose_name='حداکثر دونیت (تومان)')),
                ('alert_seconds', models.PositiveIntegerField(default=8, verbose_name='مدت نمایش آلارم (ثانیه)')),
                ('tts_enabled', models.BooleanField(default=True, verbose_name='خواندن پیام در OBS')),
                ('list_size', models.PositiveSmallIntegerField(default=8, verbose_name='تعداد آیتم لیست حامیان')),
                ('alert_gif', models.FileField(blank=True, upload_to='alerts/', verbose_name='گیف آلارم')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
