# Generated by Django 6.1 on 2026-08-29 22:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='emoji',
            field=models.CharField(blank=True, max_length=16, verbose_name='شکلک'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='accent_color',
            field=models.CharField(default='#7c5cff', max_length=9, verbose_name='رنگ اصلی'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='alert_sound',
            field=models.FileField(blank=True, upload_to='sounds/', verbose_name='صدای دونیت'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='alert_style',
            field=models.CharField(choices=[('classic', 'کلاسیک'), ('neon', 'نئون'), ('glass', 'شیشه\u200cای'), ('banner', 'بنر پایین'), ('comic', 'حباب پیام')], default='neon', max_length=20, verbose_name='ظاهر آلارم'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='alert_volume',
            field=models.PositiveSmallIntegerField(default=80, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='صدای دونیت'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatar/', verbose_name='آواتار'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bio',
            field=models.CharField(blank=True, default='اگر از استریم لذت می\u200cبری، حمایت کن تا ادامه بدم.', max_length=220, verbose_name='توضیح کوتاه درگاه'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='emoji_pack',
            field=models.CharField(default='🔥,❤️,💎,👑,⚡,🎮,💜,🌟,🙌,💯', max_length=80, verbose_name='شکلک\u200cها'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gateway_theme',
            field=models.CharField(choices=[('midnight', 'نیمه\u200cشب بنفش'), ('aurora', 'شفق'), ('royal', 'طلایی سلطنتی'), ('ember', 'آتشی'), ('ocean', 'اقیانوسی')], default='midnight', max_length=20, verbose_name='تم درگاه'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='goal_style',
            field=models.CharField(choices=[('bar', 'نوار افقی'), ('ring', 'حلقه'), ('crystal', 'کریستالی'), ('split', 'اعداد جدا')], default='crystal', max_length=20, verbose_name='ظاهر هدف'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='list_style',
            field=models.CharField(choices=[('stack', 'لیست عمودی'), ('cards', 'کارت\u200cها'), ('ticker', 'نوار متحرک'), ('pills', 'قرص\u200cهای رنگی')], default='stack', max_length=20, verbose_name='ظاهر لیست'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_goal_on_gateway',
            field=models.BooleanField(default=True, verbose_name='نمایش هدف روی درگاه'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_recent_on_gateway',
            field=models.BooleanField(default=True, verbose_name='نمایش حامیان روی درگاه'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sound_enabled',
            field=models.BooleanField(default=True, verbose_name='پخش صدای دونیت'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tts_volume',
            field=models.PositiveSmallIntegerField(default=85, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='صدای خواندن'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='alert_seconds',
            field=models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(30)], verbose_name='مدت آلارم (ثانیه)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='list_size',
            field=models.PositiveSmallIntegerField(default=8, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(20)], verbose_name='تعداد لیست حامیان'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tts_enabled',
            field=models.BooleanField(default=True, verbose_name='خواندن پیام'),
        ),
    ]
