# Generated by Django 6.1 on 2026-08-29 22:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_donation_emoji_sitesettings_accent_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_toman', models.PositiveIntegerField(verbose_name='از مبلغ')),
                ('max_toman', models.PositiveIntegerField(default=0, verbose_name='تا مبلغ (۰ یعنی بی\u200cنهایت)')),
                ('label', models.CharField(blank=True, max_length=40, verbose_name='نام شرط')),
                ('duration', models.PositiveIntegerField(default=8, verbose_name='مدت (ثانیه)')),
                ('style', models.CharField(blank=True, max_length=20, verbose_name='ظاهر')),
                ('gif', models.FileField(blank=True, upload_to='alerts/', verbose_name='گیف این بازه')),
                ('sound', models.FileField(blank=True, upload_to='sounds/', verbose_name='صدای این بازه')),
            ],
            options={
                'verbose_name': 'شرط آلارم',
                'verbose_name_plural': 'شرط\u200cهای آلارم',
                'ordering': ['min_toman'],
            },
        ),
        migrations.AddField(
            model_name='donation',
            name='show_in_list',
            field=models.BooleanField(default=True, verbose_name='نمایش در لیست'),
        ),
        migrations.AddField(
            model_name='donation',
            name='show_message',
            field=models.BooleanField(default=True, verbose_name='نمایش پیام'),
        ),
        migrations.AddField(
            model_name='donation',
            name='show_name',
            field=models.BooleanField(default=True, verbose_name='نمایش نام'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='censor_enabled',
            field=models.BooleanField(default=False, verbose_name='سانسور فعال'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='censor_mode',
            field=models.CharField(choices=[('star', 'ستاره\u200cگذاری کلمه'), ('skip', 'عدم نمایش روی استریم')], default='star', max_length=8, verbose_name='نوع سانسور'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='censor_words',
            field=models.TextField(blank=True, verbose_name='کلمات سانسور (با کاما یا خط جدید)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram',
            field=models.CharField(blank=True, max_length=160, verbose_name='اینستاگرام'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='preset_amounts',
            field=models.CharField(default='10000,20000,50000,100000,200000,500000', max_length=120, verbose_name='مبالغ پیشنهادی'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='require_terms',
            field=models.BooleanField(default=True, verbose_name='تیک قوانین روی درگاه'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram',
            field=models.CharField(blank=True, max_length=160, verbose_name='تلگرام'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tts_pitch',
            field=models.FloatField(default=1.0, verbose_name='زیر و بمی صدا'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tts_rate',
            field=models.FloatField(default=1.0, verbose_name='سرعت خواندن'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='youtube',
            field=models.CharField(blank=True, max_length=160, verbose_name='یوتیوب'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='list_size',
            field=models.PositiveSmallIntegerField(default=8, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='تعداد لیست حامیان'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='list_style',
            field=models.CharField(choices=[('stack', 'لیست عمودی'), ('cards', 'کارت\u200cها'), ('ticker', 'نوار افقی متحرک'), ('pills', 'قرص\u200cهای رنگی')], default='stack', max_length=20, verbose_name='ظاهر لیست'),
        ),
    ]
