# Generated by Django 6.1 on 2026-08-29 22:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_alertcondition_donation_show_in_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='alert_name_size',
            field=models.PositiveSmallIntegerField(default=22, validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(48)], verbose_name='اندازه نام آلارم'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='alert_text',
            field=models.CharField(default='#ffffff', max_length=9, verbose_name='رنگ متن آلارم'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='goal_active',
            field=models.BooleanField(default=True, verbose_name='هدف فعال'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='goal_bar_height',
            field=models.PositiveSmallIntegerField(default=22, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(48)], verbose_name='ارتفاع نوار'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='goal_baseline_toman',
            field=models.PositiveIntegerField(default=0, verbose_name='پایه ریست'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='goal_bg',
            field=models.CharField(default='#ffffff', max_length=9, verbose_name='رنگ پشت ویجت'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='goal_details_tpl',
            field=models.CharField(default='<CURRENT> از <GOAL> تومان', max_length=80, verbose_name='قالب جزئیات'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='goal_fill',
            field=models.CharField(default='#7c4dff', max_length=9, verbose_name='رنگ پرشدگی'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='goal_font_size',
            field=models.PositiveSmallIntegerField(default=18, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(40)], verbose_name='اندازه نوشته'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='goal_radius',
            field=models.PositiveSmallIntegerField(default=16, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)], verbose_name='گردی گوشه'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='goal_show_details',
            field=models.BooleanField(default=True, verbose_name='نمایش جزئیات هدف'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='goal_show_title',
            field=models.BooleanField(default=True, verbose_name='نمایش عنوان هدف'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='goal_start_toman',
            field=models.PositiveIntegerField(default=0, verbose_name='شروع نوار (تومان)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='goal_text',
            field=models.CharField(default='#3b0764', max_length=9, verbose_name='رنگ نوشته هدف'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='goal_title_tpl',
            field=models.CharField(default='هدف: <NAME>', max_length=80, verbose_name='قالب عنوان'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='goal_track',
            field=models.CharField(default='#e9e1ff', max_length=9, verbose_name='رنگ پس\u200cزمینه نوار'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='list_bg',
            field=models.CharField(default='#ffffff', max_length=9, verbose_name='رنگ پشت لیست'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='list_text',
            field=models.CharField(default='#2e1065', max_length=9, verbose_name='رنگ متن لیست'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='alert_style',
            field=models.CharField(choices=[('classic', 'کلاسیک'), ('neon', 'نئون'), ('glass', 'شیشه\u200cای ریمیت'), ('banner', 'بنر پایین'), ('comic', 'حباب پیام')], default='glass', max_length=20, verbose_name='ظاهر آلارم'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='goal_style',
            field=models.CharField(choices=[('bar', 'نوار افقی'), ('ring', 'حلقه'), ('crystal', 'کریستالی'), ('split', 'اعداد جدا')], default='bar', max_length=20, verbose_name='ظاهر هدف'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='list_style',
            field=models.CharField(choices=[('stack', 'لیست عمودی'), ('cards', 'کارت\u200cها'), ('ticker', 'نوار افقی متحرک'), ('pills', 'قرص\u200cهای رنگی')], default='cards', max_length=20, verbose_name='ظاهر لیست'),
        ),
    ]
