# Generated by Django 6.1 on 2026-08-29 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_goal_visual_and_overlay_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='max_amount_toman',
            field=models.PositiveIntegerField(default=100000000, verbose_name='حداکثر دونیت (تومان)'),
        ),
    ]
